var trabajos = [
    {    Anio : "Nombre y Apellido",
      Empresa  : "Ayrton Cisneros",
    Posicion : "CAMPEONES 8VA DIVISION"},
	{    Anio : "Posicion",
    Empresa  : "Mediocampista",
  Posicion : "CAMPEONES 7MA DIVISION"},
    {    Anio : "Edad",
    Empresa  : "27",
  Posicion : "CAMPEONES 7MA DIVISION"},
    {    Anio : "Peso",
      Empresa  : "75 kg",
    Posicion : "CAMPEONES DEL TORNEO REGIONAL"},
    {    Anio : "Altura",
      Empresa  : "1,85 m",
    Posicion : "CAMPEONES DE LA COPA REGIONAL"},
    {    Anio : "Partidos Jugados",
      Empresa  : "66",
    Posicion : "CAMPEONES DEL TORNEO REGIONAL"},
    {    Anio : "Goles Convertidos",
      Empresa  : "12",
    Posicion : "CAMPEONES DE 4TA DIVISIÓN"},
	 {    Anio : "Titulos ganados",
      Empresa  : "1",
    Posicion : "CAMPEONES DE 4TA DIVISIÓN"}];