var trabajos = [
    {    Anio : "2002",
      Empresa  : "Categoria 1992",
    Posicion : "CAMPEONES 8VA DIVISION"},
	{    Anio : "1996",
    Empresa  : "Categoria 1987",
  Posicion : "CAMPEONES 7MA DIVISION"},
    {    Anio : "1986",
    Empresa  : "Ctegoria 1978",
  Posicion : "CAMPEONES 7MA DIVISION"},
    {    Anio : "1980",
      Empresa  : "Plantel Profesional",
    Posicion : "CAMPEONES DEL TORNEO REGIONAL"},
    {    Anio : "1978",
      Empresa  : "Plantel Profesional",
    Posicion : "CAMPEONES DE LA COPA REGIONAL"},
    {    Anio : "1972",
      Empresa  : "Plantel de Reserva",
    Posicion : "CAMPEONES DEL TORNEO REGIONAL"},
    {    Anio : "1963",
      Empresa  : "Categoria 1946",
    Posicion : "CAMPEONES DE 4TA DIVISIÓN"},
	 {    Anio : "1960",
      Empresa  : "Categoria 1942",
    Posicion : "CAMPEONES DE 4TA DIVISIÓN"}];