var trabajos = [
    {    Anio : "2020",
      Empresa  : "Cilsa",
    Posicion : "Desarrollo Front End"},
    {    Anio : "2020",
    Empresa  : "Fundacion Telefonica",
  Posicion : "Programacion con Java Standard"},
    {    Anio : "2020",
      Empresa  : "Cilsa",
    Posicion : "Marketing Digital y wordpress"},
    {    Anio : "2019",
      Empresa  : "Terciario Urquiza",
    Posicion : "Tecnico Superior en Analisis Funcional de Sistemas Informaticos"},
    {    Anio : "2019",
      Empresa  : "Comunidad IT",
    Posicion : "Introduccion a la proramacion web"},
    {    Anio : "2016",
      Empresa  : "Escuela 404 Dr Lisandro De La Torre",
    Posicion : "Secundario con orientación Informatica"}];